# General Settings
name: Jeremy Hamilton
job_title: Javascript Developer
email: contact@jeremyhamilton.tech
description: I am a Junior Javascript Developer in Spokane, WA. I spend my free time with my family, out walking, or just buried neck-deep in code.
avatar: //www.gravatar.com/avatar/1f3ae997d0dca34957489907cf84934d?s=140
favicon: /favicon.ico
twitter_handler: zibidibodel
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'https://twitter.com/Zibidibodel' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/jeremy-hamilton-b97a7a77/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/fourmatsee' }
-  { name: codepen, url: 'https://codepen.io/Zibidibodel/' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "http://jeremyhamilton.tech"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: date
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
